version: '3'

env:
  ENV: unknown_ae
  REPO_ROOT_DIR:
    sh: "git rev-parse --show-toplevel"

# dotenv: ['.env']


includes:
  db: 
    taskfile: ./db/Taskfile.yml
    dir: ./db
  langs: 
    taskfile: ./langs/Taskfile.yml
    dir: ./langs
  back: 
    taskfile: ./backend/Taskfile.yml
    dir: ./backend


tasks:

  compose-down:
    env:
      TAG:
        # Grab the tag from the running container
        sh: docker ps | awk '{print $2}' | grep -Po '(?<=anderserik/praedict-backend:)\d\.\d\.\d'
    cmds:
      - docker compose down

  compose-prod-up-next:
    env:
      TAG:
        sh: curl -s https://hub.docker.com/v2/repositories/anderserik/praedict-backend/tags?page_size=5 | jq -r '.results[0].name' | awk -F. -v OFS=. '{$NF+=1; print}'
    cmds:
      - docker compose up -d 

  compose-dev-up-next:
    env:
      TAG:
        sh: curl -s https://hub.docker.com/v2/repositories/anderserik/praedict-backend/tags?page_size=5 | jq -r '.results[0].name' | awk -F. -v OFS=. '{$NF+=1; print}'
    cmds:
      - docker compose up 

  compose-dev:
    env:
      TAG:
        # latest
        sh: curl -s https://hub.docker.com/v2/repositories/anderserik/praedict-backend/tags?page_size=5 | jq -r '.results[0].name'
    cmds:
      - docker compose -f ./docker-compose/dev-compose.yaml up

  build:
    deps:
      - assets
    cmds:
      - echo "BUILDING"
      - task: assets

  assets:
    cmds:
      - echo "ASSETS"

  default:
    cmds: 
      - echo {{.ROOT_DIR}}
      - echo "DEFAULT"
      - echo "=============================="
      - echo "Environment Info:"
      - echo Taskfile Directory = {{.ROOT_DIR}}
      - echo Running Task = {{.TASK}}
      - echo "=============================="
      # silent: true
